### ISSUE TITLE
nice. but...

### ISSUE THREAD

**Issue by jonathan-annett** [demogorgonz/RaspberryPi-CPUMiner#1]
you might want to change "make" to "sudo make" in build.sh

doing that allowed me to sucessfull build it on an "orange pi zero" running armbian.

**Comment by demogorgonz** [comment]
Thanks for the feedback, I have corrected it. I usually run builds as root so `sudo` wasn't necessary :smiley: .
https://github.com/demogorgonz/RaspberryPi-CPUMiner/commit/5f506bafd82a796415e479da10e30fc129b1010a

**Comment by demogorgonz** [comment]
https://github.com/demogorgonz/RaspberryPi-CPUMiner/commit/5f506bafd82a796415e479da10e30fc129b1010a
