### ISSUE TITLE
Error running ./miner -h

### ISSUE THREAD

**Issue by wolfifuur** [demogorgonz/RaspberryPi-CPUMiner#10]
pi@raspberrypi:~ $ ./minerd -h
./minerd: /usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./minerd)

Got that error from my Pi Zero W console over SSH. Running latest release of Rasbian

**Comment by demogorgonz** [comment]
Try running first:

`apt install -y libcurl3 libcurl-openssl1.0-dev`

Then re-try `./minerd`

**Comment by demogorgonz** [comment]
Closing the issue, if you still have problem feel free to reply.

**Comment by Cryptominer937** [comment]
sudo apt install -y libcurl3 libcurl-openssl1.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4

E: Package 'libcurl3' has no installation candidate
E: Unable to locate package libcurl-openssl1.0-dev
E: Couldn't find any package by glob 'libcurl-openssl1.0-dev'
E: Couldn't find any package by regex 'libcurl-openssl1.0-dev'

**Comment by demogorgonz** [comment]
@Cryptominer937 

From your output:
_However the following packages replace it:
libcurl4_

`apt-get install libcurl4 libcurl4-openssl-dev` 

try that 😄
