### ISSUE TITLE
Compiled from newalgorithms - 0 Hashrate (PI 3)

### ISSUE THREAD

**Issue by andyjk15** [demogorgonz/RaspberryPi-CPUMiner#6]
Getting 0 H/s when compiling from newalgorithms for a raspberry pi 3. 
<img width="599" alt="bin_ _pi_rpi0___mnt_raspberrypi-cpuminer_cpuminer-newalgorithms_ _ssh_pi_192_168_1_125_ _194x57" src="https://user-images.githubusercontent.com/6502006/34322384-b884423c-e81d-11e7-8481-d93eba37391a.png">

**Comment by gnubyte** [comment]
I'm still having this issue too.
Raspberry pi 3 as the machine.

**Comment by demogorgonz** [comment]
Seems like experimental repository is not functional, either try the previous release with old algorithms or wait a bit until i find some free time to test another repo and compile for RPI.

Link to regular [miner](https://github.com/demogorgonz/RaspberryPi-CPUMiner/releases/tag/v.1.0)
