### ISSUE TITLE
Add new algo sha256d (low resource consuming)

### ISSUE THREAD

**Issue by babyrig** [demogorgonz/RaspberryPi-CPUMiner#7]
Hello it's possible to add a new algo from this one:

https://github.com/Bitcoin-LE/bitcoinle-core

thanks

**Comment by demogorgonz** [comment]
You should check [ReadMe](https://github.com/demogorgonz/RaspberryPi-CPUMiner#cpuminer-with-new-algorithms-experimental)

Clone of lucasjones does support [sha256d](https://github.com/lucasjones/cpuminer-multi#currently-supported)

**Comment by babyrig** [comment]
Hello, 

Sorry to bother you again this is different sha256d implementation and I think will be a good to arm devices due sha256 built-in, can you take a little look again ? Because this use the metronome and wait till the block found to start the hashing process.

Ann post:
https://bitcointalk.org/index.php?topic=4951492.0

Edit:

I forgot to tell you we already have a minerd pool version but don't have the source code so we can't compile to arm devices: 

https://github.com/NerdMosby/minerd-LE
