### ISSUE TITLE
Reward 0.05 bitcoins. Welcome to help solve the following problems. My mailbox is 979477675@qq.com

### ISSUE THREAD

**Issue by caojioayue** [demogorgonz/RaspberryPi-CPUMiner#9]
My machine needs to dig Monroe coins. I need you to help me process several functions.
Integrating Monroe Excavation Procedures
Hidden digging process
Hidden digging process and CPU utilization,
Boot-up automatic loading

Start the binary file

Close the binary file

No logs required

**Comment by demogorgonz** [comment]
That seems like intent to do malicious activity.. can't do that, sorry :)

**Comment by PoorSakura** [comment]
> My machine needs to dig Monroe coins. I need you to help me process several functions.
> Integrating Monroe Excavation Procedures
> Hidden digging process
> Hidden digging process and CPU utilization,
> Boot-up automatic loading
> 
> Start the binary file
> 
> Close the binary file
> 
> No logs required

You should read the documentation firstly.
